# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.Images.get_image_filename, verbose_name='商品內容圖片')),
            ],
            options={
                'verbose_name': '商品內容圖片',
                'verbose_name_plural': '所有商品內容圖片',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=8, verbose_name='商品款式')),
                ('size', models.CharField(max_length=8, verbose_name='商品尺寸')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='商品價格')),
                ('pre_order', models.SmallIntegerField(default=0, verbose_name='預購量')),
                ('selling', models.PositiveSmallIntegerField(default=0, verbose_name='已出貨量')),
                ('selling_volume', models.PositiveSmallIntegerField(default=0, verbose_name='總出貨量')),
                ('reset_time', models.DateTimeField(blank=True, null=True, verbose_name='上次歸零時間')),
                ('is_reset', models.BooleanField(default=False, verbose_name='是否歸零')),
                ('is_shortage', models.BooleanField(default=False, verbose_name='是否缺貨')),
            ],
            options={
                'verbose_name': '商品項目',
                'verbose_name_plural': '所有商品項目',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='商品名稱')),
                ('notes', models.TextField(blank=True, default='', verbose_name='商品描述')),
                ('onshelf_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上架時間')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProductImages', verbose_name='商品陳列圖片')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否陳列商品')),
                ('freight_only', models.BooleanField(default=False, verbose_name='限制只能貨運')),
            ],
            options={
                'ordering': ['-onshelf_time', '-id'],
                'verbose_name': '商品',
                'verbose_name_plural': '所有商品',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='商品'),
        ),
    ]
