# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': '內容', 'verbose_name_plural': '所有內容'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date', 'raiser'], 'verbose_name': '商品', 'verbose_name_plural': '所有商品'},
        ),
        migrations.AlterField(
            model_name='detail',
            name='color',
            field=models.CharField(max_length=10, verbose_name='商品樣式'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.PositiveIntegerField(verbose_name='商品價格'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.Product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='size',
            field=models.CharField(max_length=10, verbose_name='商品尺寸'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='刊登日期'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages', verbose_name='商品圖片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='展示與否'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='raiser',
            field=models.PositiveIntegerField(verbose_name='募集人數'),
        ),
    ]
