# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160720_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='商品'),
        ),
    ]
