# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': '商品圖片', 'verbose_name_plural': '所有商品圖片'},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=products.models.get_image_filename, verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='raiser',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='募集人數'),
        ),
    ]
