# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20161010_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_image_filename, verbose_name='商品內容圖片'),
        ),
    ]
