# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20161013_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date'], 'verbose_name': '商品', 'verbose_name_plural': '所有商品'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='raiser',
        ),
        migrations.AddField(
            model_name='detail',
            name='sold',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='銷貨'),
        ),
        migrations.AddField(
            model_name='detail',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='存貨'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='商品價格'),
        ),
    ]
