# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20161015_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='total_sold',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='總已銷貨量'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='sold',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='已銷貨量'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='存貨量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages', verbose_name='商品展示圖片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='是否展示商品'),
        ),
    ]
