# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20160827_1942'),
        ('members', '0003_auto_20160925_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='訂單編號')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='訂購時間')),
                ('freight', models.PositiveIntegerField(verbose_name='運費')),
                ('total', models.PositiveIntegerField(verbose_name='運費')),
                ('notes', models.TextField(max_length=200, verbose_name='備註')),
                ('status', models.CharField(choices=[('UP', '待付款/匯款'), ('PA', '通知已付款'), ('PC', '確認已付款'), ('WS', '商品準備中'), ('SN', '商品已寄出'), ('AB', '放棄此訂單'), ('AC', '待賣家確認放棄'), ('AD', '已放棄')], default='UP', max_length=2)),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.PersonalInfo', verbose_name='買家')),
                ('sold_goods', models.ManyToManyField(to='products.Detail', verbose_name='已買商品')),
            ],
            options={
                'verbose_name_plural': '所有購物清單',
                'ordering': ['-order_date'],
                'verbose_name': '購物清單',
            },
        ),
    ]
