# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='訂單編號')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='訂購時間')),
                ('freight', models.PositiveSmallIntegerField(verbose_name='運費')),
                ('ship_method', models.CharField(choices=[('FML', '全家'), ('KTJ', '大榮貨運')], default='KTJ', max_length=3, verbose_name='運送方式')),
                ('address', models.CharField(default='', max_length=64, verbose_name='寄送地址')),
                ('total', models.PositiveIntegerField(verbose_name='總額')),
                ('buyer_notes', models.TextField(default='', verbose_name='備註')),
                ('status', models.CharField(choices=[('UPD', '待付款/匯款'), ('PAD', '通知已付款'), ('CFP', '確認已付款'), ('SPN', '商品準備中'), ('SPD', '商品已寄出'), ('ABN', '放棄此訂單'), ('CCA', '取消放棄此訂單'), ('CFA', '待賣家確認放棄'), ('ABD', '已放棄')], default='UPD', max_length=3, verbose_name='訂單狀態')),
                ('order_notes', models.TextField(default='', verbose_name='訂單清單')),
                ('remittance_account', models.CharField(default='', max_length=6, verbose_name='匯款帳號')),
                ('remittance_time', models.DateTimeField(blank=True, null=True, verbose_name='匯款日期時間')),
                ('shipment_time', models.DateTimeField(blank=True, null=True, verbose_name='寄出日期時間')),
                ('renounce_time', models.DateTimeField(blank=True, null=True, verbose_name='放棄日期時間')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.PersonalInfo', verbose_name='買家')),
                ('sold_goods', models.ManyToManyField(to='products.Item', verbose_name='已買商品')),
            ],
            options={
                'verbose_name': '購物清單',
                'ordering': ['-order_time'],
                'verbose_name_plural': '所有購物清單',
            },
        ),
    ]
