# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='shipment_number',
            field=models.CharField(default='', max_length=13, verbose_name='包裹貨件編號'),
        ),
    ]
