# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 18:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20160926_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='訂單編號'),
        ),
    ]
