# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20160926_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_notes',
            field=models.TextField(default='', verbose_name='訂單清單'),
        ),
    ]
