# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20160927_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(default='', max_length=200, verbose_name='備註'),
        ),
    ]
