# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_purchaseorder_date_remittance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_remittance',
            field=models.DateTimeField(blank=True, null=True, verbose_name='匯款日期'),
        ),
    ]
