# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20161002_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_remittance',
            field=models.DateField(blank=True, null=True, verbose_name='匯款日期'),
        ),
    ]
