# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20161013_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='date_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='寄出日期時間'),
        ),
    ]
