# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{5,6}$', '請輸入5位帳號或6位局號！')], verbose_name='匯款帳號(5碼)/無摺局號(6碼)')),
            ],
            options={
                'verbose_name': '匯款帳號/無摺局號',
                'verbose_name_plural': '所有匯款帳號/無摺局號',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=64, verbose_name='地址')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '所有地址',
            },
        ),
        migrations.CreateModel(
            name='FamilyNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', '請輸入6位全家店鋪號！')], verbose_name='全家店鋪號')),
            ],
            options={
                'verbose_name': '全家店鋪號',
                'verbose_name_plural': '所有全家店鋪號',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男性'), ('F', '女性')], default='F', max_length=1, verbose_name='性別')),
                ('birthday', models.DateField(help_text='範例：1993/11/29', verbose_name='生日')),
                ('phone', models.CharField(help_text='範例：0912456999', max_length=10, validators=[django.core.validators.RegexValidator('^09\\d{8}$', '請輸入正確的手機號碼', 'invalid')], verbose_name='手機')),
                ('email', models.EmailField(max_length=254)),
                ('money', models.PositiveIntegerField(default=0, verbose_name='儲值金')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '會員資料',
                'ordering': ['-id'],
                'verbose_name_plural': '所有會員資料',
            },
        ),
        migrations.AddField(
            model_name='familynumber',
            name='personalinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.PersonalInfo', verbose_name='會員'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='personalinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.PersonalInfo', verbose_name='會員'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='personalinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.PersonalInfo', verbose_name='會員'),
        ),
    ]
