# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='birthday',
            field=models.DateField(help_text='範例：XXXX/XX/XX', verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='儲值金'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
