# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='已消費金額'),
        ),
    ]
