# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20160925_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='address',
            field=models.TextField(default='', max_length=150, verbose_name='住址'),
            preserve_default=False,
        ),
    ]
