# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_personalinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(max_length=150, verbose_name='住址'),
        ),
    ]
