# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20160929_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名（收件人）'),
        ),
    ]
